// Generated by Cargo, it expects all of my code in 'src' folder, will check if I can find some way to use 'Source' instead
// On running 'cargo build', target & Cargo.lock are created... And I can see my executable in ./Target/Debug/HelloCargo
// Got a warning for no Snake Case as well, but I'll just do what I wanna >:)

/*
    On running "cargo run", I got the target stuff + the executable ran directly -> Pog? I think so

    On running "cargo check" however, I get nothing -> No executable, no running of code >:(
    It simply 'checks' if my code has any problems or not, IG the memes on compile time errors were true

    On running "cargo build --release", I get a dir in target called 'release',
    which according to the docs, I will be using to publish apps and stuff since it is more effecient
*/

fn main() {
    println!("Hello, world!");
}
